steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$BRANCH_NAME', './cloudrun']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$BRANCH_NAME']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', '$BRANCH_NAME', '--image', 'gcr.io/$PROJECT_ID/$BRANCH_NAME', '--region', 'us-central1','--platform', 'managed']
images:
- gcr.io/$PROJECT_ID/$BRANCH_NAME
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/sh'
  args:
  - '-curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -'
  - 'curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list'
  - 'apt-get update'
  - 'apt-get install mssql-tools -y'
  - 'sh sqlcmd.sh', '-f', './cloudrun'
 

