steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$BRANCH_NAME', './cloudrun']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$BRANCH_NAME']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', '$BRANCH_NAME', '--image', 'gcr.io/$PROJECT_ID/$BRANCH_NAME', '--region', 'us-central1','--platform', 'managed']
images:
- gcr.io/$PROJECT_ID/$BRANCH_NAME
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['bash', 'sqlcmd-backup.sh']
